In [15]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import pandas as pd
import time
import re

In [16]:
driver_path = r'chromedriver.exe'
service = Service(driver_path)
driver = webdriver.Chrome(service=service)
driver.get('https://www.imdb.com/chart/top/') 
time.sleep(2)
elements = driver.find_elements(By.TAG_NAME,'a')
text_list = [element.text for element in elements]
name_texts=[x for x in text_list if x][4:254]
elements_2 = driver.find_elements(By.CLASS_NAME,'secondaryInfo')
text_list_2 = [element.text for element in elements_2]
year_texts = [re.search(r'\((.*?)\)', text).group(1) for text in text_list_2]
elements_3 = driver.find_elements(By.XPATH,'//strong[@title]')
rating_list = [element.get_attribute('title').split(' ')[0] for element in elements_3]
df=pd.DataFrame({'Movie Name':name_texts,'Release Year':year_texts,'Rating':rating_list})

In [17]:
df

                   Movie Name Release Year Rating
0    The Shawshank Redemption         1994    9.2
1               The Godfather         1972    9.2
2             The Dark Knight         2008    9.0
3       The Godfather Part II         1974    9.0
4                12 Angry Men         1957    9.0
..                        ...          ...    ...
245                  The Help         2011    8.0
246            The Iron Giant         1999    8.0
247             Life of Brian         1979    8.0
248                   Aladdin         1992    8.0
249        Dances with Wolves         1990    8.0

[250 rows x 3 columns]